name: Publish Image

on: [push]
  # push:
  #   branches:
  #   - 'release'
  #   - 'main'

jobs:
  build-push-protogen:
    name: Build and push docker images
    uses: indrasaputra/docker-images/.github/workflows/reusable-docker.yml@test-more-platform
    with:
      image: protogen
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  
  build-push-golang:
    name: Build and push docker images
    uses: indrasaputra/docker-images/.github/workflows/reusable-docker.yml@test-more-platform
    with:
      image: golang
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
