name: Publish Image
on:
  push:
    branches:
    - 'release'

jobs:
  publish-image:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install make
      run: sudo apt-get install make

    - name: Build image
      uses: docker/build-push-action@v1
      run: make build.protogen ${{github.sha}}
      with: 
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_with_sha: true
        tag_with_ref: true 