name: Publish Image

on:
  push:
#     branches:
#     - 'release'
#     - 'main'

jobs:
  # build-push-protogen:
  #   name: Build & push protogen
  #   uses: indrasaputra/docker-images/.github/workflows/reusable-docker.yml@kadabra
  #   with:
  #     image: protogen
  #   secrets:
  #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  #     DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  
  build-push-golang:
    name: Build & push golang
    uses: indrasaputra/docker-images/.github/workflows/reusable-docker.yml@kadabra
    with:
      image: golang
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
