name: Publish Protogen

on:
  push:
    branches:
      - 'release'
      - 'main'

jobs:
  check-changes:
    uses: dorny/paths-filter@v2
    id: changes
    with:
      filters: |
        src:
          - '.github/workflows/reusable-docker.yml'
          - '.github/workflows/protogen-cd.yml'
          - 'protogen/**'

  build-push-protogen:
    name: Build & push protogen
    needs: [check-changes]
    if: ${{ steps.changes.outputs.src == 'true' }}
    uses: indrasaputra/docker-images/.github/workflows/reusable-docker.yml@main
    with:
      image: protogen
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
