name: Publish Protogen

on:
  push:
    branches:
      - "release"
      - "main"

jobs:
  check-changes:
    name: Check file changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.src }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Filter file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - '.github/workflows/reusable-docker.yml'
              - '.github/workflows/protogen-cd.yml'
              - 'protogen/**'

  build-push-protogen:
    name: Build & push protogen
    needs: [check-changes]
    if: ${{ needs.check-changes.outputs.changed == 'true' }}
    uses: indrasaputra/docker-images/.github/workflows/reusable-docker.yml@release
    with:
      image: protogen
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
