name: Reusable docker related workflow

on:
  workflow_call:
    inputs:
      image:
        description: The name of the image
        required: true
        type: string
      platforms:
        description: Platforms to build the target project
        required: false
        type: string
        default: "linux/amd64, linux/arm64, linux/arm/v7"

    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  build-push-docker:
    name: Build and push ${{ inputs.image }} image
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@vv4
      - name: Get current date
        id: date
        run: echo "::set-output name=current::$(date +'%Y-%m-%d')"
      - name: Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ github.repository_owner }}/${{ inputs.image }}
          tags: |
            type=raw,value=${{ steps.date.outputs.current }}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push ${{ inputs.image }}
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./${{ inputs.image }}/Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
